version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_container
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: collinso
      MYSQL_DATABASE: TransactionNotificationDb
      MYSQL_USER: root
      MYSQL_PASSWORD: collinso
    volumes:
      - ./mysql-dataz:/var/lib/mysql
    ports:
      - "3307:3306"

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 40s

  backend:
    build: .
    container_name: backend-container
    restart: always
    ports:
      - "8084:9000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/TransactionNotificationDb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: collinso
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
